theme: jekyll-theme-cayman
# Site wide configuration

title: AI MetabolisMX Lab
locale: en_US
logo: # filename of a logo image that has been placed into your images directory

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Omar Yaxmehen Bello-Chavolla
  avatar: images/fotoobc.jpg
  bio: "This is a sample Jekyll academic website."
  email: oyaxbell@yahoo.com.mx
  # Do not include the @ symbol in your Twitter username
  twitter: OmarBelloMD
  linkedin: #username
  github: laderast
  orcid: 0000-0003-3093-937X
  researchgate: Omar Yaxmehen Bello-Chavolla
  mendeley: #username
  google:
    scholar: kS_jiQ8AAAAJ
